# Numpy Learning

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
type(my_list)

list

In [4]:
arr = np.array(my_list)

In [5]:
type(arr)

numpy.ndarray

In [6]:
print (my_list)
print (arr)

[1, 2, 3]
[1 2 3]


Generate numbers using numpy

In [7]:
arr = np.arange(0, 11, 1)

In [8]:
print (arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


array of zeros and ones

In [9]:
print (np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
print (np.zeros((3,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
print (np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
print (np.ones((5,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Create Linearly spaced arrays - between 1 and 23 evenly spaced 40 numbers

In [13]:
print (np.linspace(1, 23, 40))

[ 1.          1.56410256  2.12820513  2.69230769  3.25641026  3.82051282
  4.38461538  4.94871795  5.51282051  6.07692308  6.64102564  7.20512821
  7.76923077  8.33333333  8.8974359   9.46153846 10.02564103 10.58974359
 11.15384615 11.71794872 12.28205128 12.84615385 13.41025641 13.97435897
 14.53846154 15.1025641  15.66666667 16.23076923 16.79487179 17.35897436
 17.92307692 18.48717949 19.05128205 19.61538462 20.17948718 20.74358974
 21.30769231 21.87179487 22.43589744 23.        ]


Random Library

In [14]:
print (np.random.randint(1, 18904, 10))

[14553 13214 13798  3121 15377 13808 16951 11253 18292 10271]


In [15]:
print (np.random.randint(12029, 102040, (10, 2)))

[[16582 64094]
 [17145 94814]
 [37312 31516]
 [28382 50051]
 [83673 88160]
 [69720 39602]
 [66232 15417]
 [91263 70928]
 [26045 35939]
 [28633 84360]]


Generate a random seed so that the random number generated is constant throughout

In [16]:
np.random.seed(101)
print (np.random.randint(12000, 120406, (2, 10)))

[[ 57919  95467  95281  85542  17695  61751  67293  89899  32463 109673]
 [ 29357  34056  99684  47391  73173  83996  90556  31566  98493  44817]]


In [17]:
np.random.seed(101)
print (np.random.randint(0, 100, 10))

[95 11 81 70 63 87 75  9 77 40]


In [18]:
print (np.random.randint(0,100,10))

[ 4 63 40 60 92 64  5 12 93 40]


In [19]:
#Always returns same
np.random.seed(101)
print (np.random.randint(0, 100, 10))

[95 11 81 70 63 87 75  9 77 40]


Array operations 

In [20]:
np.random.seed(101)
arr = np.random.randint(0, 100 , 10)

In [21]:
print (arr)

[95 11 81 70 63 87 75  9 77 40]


In [22]:
arr.max()

95

In [23]:
arr.min()

9

In [24]:
arr.mean()

60.8

In [25]:
#Index location of the max and min value
arr.argmax()

0

In [26]:
arr.argmin()

7

In [27]:
#Reshaping an array

arr.reshape(2, 5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [28]:
# arr.reshape(10,2) # This will fail as array has 10 elements

In [29]:
arr = np.linspace(1, 100, 100).reshape(10, 10)

In [30]:
print (arr)

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]
 [ 31.  32.  33.  34.  35.  36.  37.  38.  39.  40.]
 [ 41.  42.  43.  44.  45.  46.  47.  48.  49.  50.]
 [ 51.  52.  53.  54.  55.  56.  57.  58.  59.  60.]
 [ 61.  62.  63.  64.  65.  66.  67.  68.  69.  70.]
 [ 71.  72.  73.  74.  75.  76.  77.  78.  79.  80.]
 [ 81.  82.  83.  84.  85.  86.  87.  88.  89.  90.]
 [ 91.  92.  93.  94.  95.  96.  97.  98.  99. 100.]]


In [31]:
arr = np.arange(0 , 100).reshape(10, 10)

In [32]:
print (arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


Get single element from an array

In [33]:
arr[0,1]

1

In [34]:
arr[4,5]

45

In [35]:
arr[:,0] # Get first column

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
arr[0, :] #Get first row

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])