# SciKit Learn Preprocessing

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
data = np.random.randint(10,200,(10,2))

In [3]:
print (data)

[[187  16]
 [158 151]
 [183  82]
 [ 32 178]
 [ 83 129]
 [149  96]
 [196  21]
 [ 78  40]
 [ 90 137]
 [ 49  98]]


In [4]:
scaler_model = MinMaxScaler()

In [5]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [6]:
scaler_model.fit(data)

/home/abhishek/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data) #Data normalized

array([[0.94512195, 0.        ],
       [0.76829268, 0.83333333],
       [0.92073171, 0.40740741],
       [0.        , 1.        ],
       [0.31097561, 0.69753086],
       [0.71341463, 0.49382716],
       [1.        , 0.0308642 ],
       [0.2804878 , 0.14814815],
       [0.35365854, 0.74691358],
       [0.10365854, 0.50617284]])

In [8]:
scaler_model.fit_transform(data)

/home/abhishek/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.94512195, 0.        ],
       [0.76829268, 0.83333333],
       [0.92073171, 0.40740741],
       [0.        , 1.        ],
       [0.31097561, 0.69753086],
       [0.71341463, 0.49382716],
       [1.        , 0.0308642 ],
       [0.2804878 , 0.14814815],
       [0.35365854, 0.74691358],
       [0.10365854, 0.50617284]])

In [9]:
my_data = np.random.randint(0,1029304,(50,4))

In [10]:
data = pd.DataFrame(data = my_data, columns=['f1','f2','f3','label'])

In [11]:
data

f1       f2       f3   label
0   860021   800894   208835  183948
1    31419  1026367   162352  458881
2   851923    27684   752343   68784
3   651977   748393   228719  237959
4    39909   566187   795526  514795
5   271615   120782   297938  968889
6   534103   809825   435581  178796
7   682652   383844   415351  622594
8   996816   673396   808829  757007
9   261472   743504     9720  525537
10  801370   661756    79007  185838
11  697713   821257   207267  645514
12  602586   450082   357908  767457
13  830990  1019015   209522  511576
14  691432   986670   859271  138540
15  596792   134637   163603   37371
16  236344   260072    33472  129950
17  996726   594310   558530  213625
18  572344    21620   511085   82496
19    2074   765970   639759  619952
20  247290    63807   994111  768993
21  722134   820881   823729   88729
22  444333   635562   174284   22260
23  913692   883875   877837  986571
24   24198   285498   999665  224849
25  309198   903663   901616  377558
26  621220   980764   674619  116724
27  374255   413034   966797  600245
28  839425   550655   550872   98836
29  957590   607724   800065  601229
30   84238   295358   419119  506015
31  407082   322088   645356  383654
32  387951   721056   467585  437447
33  821374   447503   593776  562075
34  990567   751931   321177  116667
35  220543   797820   108097  128589
36  703122   637001   846898  286931
37  829232   711378   554632  374037
38   73697   416262   115881  471001
39  944512   760396   770954  120390
40  362816    63371  1014211  680309
41  590243   664188   741930  253666
42  592219   611632    29759  115748
43  321554   317556   321598  729665
44  831933   663014   623857   12587
45    8310   196188   382675  217849
46  892538   354660   347122  799588
47  357796   906482   648391   51443
48  174516   165103   277551  739021
49  905559   264047   511519  562672

In [12]:
X = data[['f1','f2','f3']]
Y = data['label']

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 42)

In [14]:
X_train.shape

(35, 3)

In [15]:
X_test.shape

(15, 3)